main: com.cavetale.tutor.TutorPlugin
name: Tutor

version: 0.1
api-version: 1.18

description: Player Tutorials
author: StarTux
website: https://github.com/StarTux/Tutor

depend: [Core, SQL, Perm, PlayerCache, Sidebar, Mytems, ProtocolLib, Ticket]
softdepend: []

commands:

  tutor:
    aliases: [tut, quest, q]
    description: Tutor Command
    permission: tutor.tutor
    usage: |-
      /tutor

  tutoradmin:
    aliases: [tutoradm]
    description: Admin command
    permission: tutor.admin
    usage: |-
      /tutoradmin

permissions:

  tutor.tutor:
    description: Use /tutor
    default: op

  tutor.admin:
    description: Use /tutoradmin
    default: op

  tutor.beginner:
    description: Auto start the beginner quest
    default: false